services:
  - postgres:10

variables:
  POSTGRES_DB: bharat_test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test

before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install

tests:
  script:
    - rails test

static-code-analysis:
  script:
    - rubocop