version: '2.0'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    command: bash -c "ruby scripts/server.rb && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/bharat
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db