default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: 127.0.0.1

development:
  <<: *default
  database: bharat_dev
  username: postgres
  password: postgres

test:
  <<: *default
  database: bharat_test
  username: test
  password: test

production:
  <<: *default
  database: bharat
  username: postgres
  password: postgres

