default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: bharat_dev
  username: postgres
  password: pass

test:
  <<: *default
  database: bharat_test
  username: postgres
  password: pass

production:
  <<: *default
  database: bharat
  username: postgres
  password: pass

