default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: db

development:
  <<: *default
  database: bharat_dev
  username: postgres
  password: postgres

test:
  <<: *default
  database: bharat_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: bharat
  username: postgres
  password: postgres

